spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password:

# Elasticsearch configuration
elasticsearch:
  # Enable Elasticsearch? Set to false if Elasticsearch is not installed locally
  open: false
  # Elasticsearch cluster name
  clusterName: elasticsearch
  hosts: 127.0.0.1:9200
  userName: elastic
  password: elastic
  # Elasticsearch request method
  scheme: http
  # Elasticsearch connection timeout
  connectTimeOut: 1000
  # Elasticsearch socket connection timeout
  socketTimeOut: 30000
  # Elasticsearch request timeout
  connectionRequestTimeOut: 500
  # Elasticsearch maximum number of connections
  maxConnectNum: 100
  # Elasticsearch maximum number of connections per route
  maxConnectNumPerRoute: 100
